### ISSUE TITLE
pending-author.t is not happy

### ISSUE THREAD

**Issue by remorse** [haukex/webperl#11]
**Describe the bug**
I was trying to compile webperl, so that I can add some additional modules (although I haven't got that far yet), and the compile failed because my "git" name is not in the "authors" file.

**To Reproduce**
I was following the instructions on the website, and `./build/build.pl` was going along gangbusters, and then it failed:

		t/porting/pending-author ....................................... Ricky Morse  <remorse@mgh.harvard.edu> not found in AUTHORS
		FAILED at test 1

...

		Failed 1 test out of 2467, 99.96% okay.
			porting/pending-author.t
		### Since not all tests were successful, you may want to run some of
		### them individually and examine any diagnostic messages they produce.
		### See the INSTALL document's section on "make test".
		### You have a good chance to get more information by running
		###   ./perl harness
		### in the 't' directory since most (>=80%) of the tests succeeded.
		### You may have to set your dynamic library search path,
		### DYLD_LIBRARY_PATH, to point to the build directory:
		###   setenv DYLD_LIBRARY_PATH `pwd`; cd t; ./perl harness
		###   DYLD_LIBRARY_PATH=`pwd`; export DYLD_LIBRARY_PATH; cd t; ./perl harness
		###   export DYLD_LIBRARY_PATH=`pwd`; cd t; ./perl harness
		### for csh-style shells, like tcsh; or for traditional/modern
		### Bourne-style shells, like bash, ksh, and zsh, respectively.
		Elapsed: 620 sec
		u=4.62  s=2.83  cu=334.57  cs=45.55  scripts=2467  tests=1158999
		make: *** [test] Error 1
		Command "make" failed: exit status 2 at ./build/build.pl line 206.

**Expected behavior vs. actual behavior**
I had hoped it would compile.

**Versions**
 - Device: compiling on Mac OS X 10.13.6
 - Perl: 5.28, it seems
 - Emscripten: 1.38.21-64bit

**Comment by haukex** [comment]
Hi, thanks for the report. I guess you've made some changes to the source and committed them? In that case, have you tried adding the line `Ricky Morse  <remorse@mgh.harvard.edu>` to the `AUTHORS` file and committing that too?

**Comment by remorse** [comment]
I haven't made any changes -- I thought there were some that were made by the Webperl system? But I haven't made any changes myself, beyond setting the correct path for `emsdk_env.sh`...

**Comment by haukex** [comment]
Hmmm, perhaps the patches that `build.pl` applies use the current author, I'll have to look into that...

**Comment by haukex** [comment]
Inside the `webperl` directory, could you do the following and report back the output? `cd emperl5` and `git log --pretty='%h %an <%ae> %s%d' v5.28.0..` TIA!

**Comment by remorse** [comment]
Hi! I ran the command, and all of the commits were authored by you. However, I had hacked past the build process, and I think there were some weird things going on, so I'm going to run it again.

Oddly, `git` is now reporting everything in Russian, so I'm not sure what is going on, and I don't actually have direct access to the computer at this moment (I technically am on vacation, this is my work computer, and although I can ssh in, I can't go in for a while). I'll report back once I have re-run the process, and not tried to hack through it.

**Comment by haukex** [comment]
I tried changing the git author setting, but haven't been able to reproduce the issue on my end yet. So if by "hacked past the build process" you mean you've made changes, then it would be best if you could let me know the exact steps to reproduce this issue, starting with a clean `webperl` checkout.

Note that [`t/porting/pending-author.t`](https://github.com/Perl/perl5/blob/blead/t/porting/pending-author.t) says: "This uses Porting/checkAUTHORS.pl to check that any pending commit isn't about to break t/porting/authors.t" - so it's not just changes that have already been committed, but any uncommitted changes too. So you should probably still add yourself to the `AUTHORS` file and commit that - let me know if that fixes it.

**Comment by haukex** [comment]
Hi @remorse, have you had a chance to try out the fixes I suggested here and in #12?

**Comment by haukex** [comment]
Closing for now; can be re-opened if necessary.
