### ISSUE TITLE
webperl waits for process to finish

### ISSUE THREAD

**Issue by donno2048** [haukex/webperl#20]
## Describe the bug

```js
Perl.makeOutputTextarea()
```

Won't work with loop because it waits for finished execution

## To Reproduce

Include _emperl.*_ in the folder as well as _webperl.js_ and this _index.html_:

```html
<!DOCTYPE html>
<html>
    <head>
        <script src="./webperl.js"></script>
        <script type="text/perl" src="./main.pl">
        </script>
        <script>
            window.addEventListener("load", function () {document.body.appendChild(Perl.makeOutputTextarea());});
        </script>
    </head>
    <body></body>
</html>
```

And this _main.pl_:

```perl
while(1){
  print "1"
}
```

## Expected behavior vs. actual behavior

I would expect the created textarea to update continuously but instead the tab freeze.

**Comment by haukex** [comment]
This is the same behavior as JavaScript, and is expected - any running JavaScript blocks the browser. This is a fundamental issue with JS, and WebAssembly and therefore WebPerl acts the same way. I talked about this a little bit in my talk at this timestamp: <https://youtu.be/bT17TCMbsdc?t=1094>

If you want some element of the page to update continuously, one solution is to set a timer and have the code execute in the timer event. But more commonly, one would set up event handlers to react to events like input from the user and communication from the webserver.

This JavaScript example blocks the browser:
```html
<script>
    "use strict";
    window.addEventListener('load', function () {
        while(true) {
            console.log("1");
        }
    });
</script>
```

This Perl code does not:
```perl
use warnings;
use strict;
use WebPerl 'js';

my $window = js('window');

# print "1" every 10ms and stop after 100 prints
my $count = 0;
my $id; $id = $window->setInterval(sub {
		print "1";
		$window->clearInterval($id) if ++$count>=100;
	}, 10);
```

**Comment by donno2048** [comment]
Makes sense, thanks!
