### ISSUE TITLE
missing module Digest::MD5

### ISSUE THREAD

**Issue by AlDanial** [haukex/webperl#5]
This is a pretty amazing project!  For fun I wanted to see how much of https://github.com/AlDanial/cloc I could run in the browser. I changed ``webperl_demo.html`` to 
<pre>
<script type="text/perl">
use Digest::MD5;
print "Hello, Perl World!\n";
</script>
</pre>

and got the error 
<pre>
Can't locate Digest/MD5.pm in @INC (you may need to install the Digest::MD5 module) (@INC contains: /opt/perl/lib/site_perl/5.28.0/wasm /opt/perl/lib/site_perl/5.28.0 /opt/perl/lib/5.28.0/wasm /opt/perl/lib/5.28.0) at /tmp/scripts.pl line 13.
BEGIN failed--compilation aborted at /tmp/scripts.pl line 13.
exit(2) called, but NO_EXIT_RUNTIME is set, so halting execution but not exiting the runtime or preventing further async execution (build with NO_EXIT_RUNTIME=0, if you want a true shutdown)
</pre>

I realize you can't possibly include all of CPAN's modules in your wasm collection, but perhaps you could add some of the more popular ones?

**Comment by haukex** [comment]
Thanks! Since it's a core module anyway, I don't mind adding it in (assuming I don't have too much trouble compiling it) - I'll look into this for the next release.

**Comment by haukex** [comment]
The issue won't entirely be closed until I actually publish the release.

**Comment by haukex** [comment]
WebPerl `v0.09-beta` has been released, which includes `Digest::MD5` and `Digest::SHA`.
