### ISSUE TITLE
Regex Tester can produce "subroutine redefined" warnings

### ISSUE THREAD

**Issue by haukex** [haukex/webperl#9]
... if the Preamble Code contains `sub`s. For example: <https://www.perlmonks.org/?node_id=1225457>

**Comment by SREagle1** [comment]
Is this really an issue? Both "no warnings 'redefine'" and use of coderefs / anonymous subs can mitigate the symptom. Nice project, btw.

**Comment by haukex** [comment]
Thanks! And no, it's not really an issue, I just wrote it up so that I remember to think about whether there might be an elegant solution, but most recently I was thinking to just leave it as it is.
